export const themes = [
  {
    id: 'light-parchment',
    label: 'Пергамент',
    group: 'light',
    description: 'Ink & Teal. Тёплая бумага и спокойный бирюзовый акцент — книжная тема по умолчанию.',
    accent: '#0e7c70',
    bg: '#f6f3ec',
    surface: '#fdfbf6',
    text: '#1c1917',
  },
  {
    id: 'dark-parchment',
    label: 'Пергамент',
    group: 'dark',
    description: 'Ink & Teal. Тёмный вариант пергамента с мягким бирюзовым свечением.',
    accent: '#4bc3b6',
    bg: '#16140f',
    surface: '#1f1c16',
    text: '#e8e2d6',
  },
  {
    id: 'light-slate',
    label: 'Пепел',
    group: 'light',
    description: 'Slate & Amber. Нейтральный серый фон и тёплый янтарный акцент.',
    accent: '#b45309',
    bg: '#f5f5f4',
    surface: '#ffffff',
    text: '#1c1c1e',
  },
  {
    id: 'dark-slate',
    label: 'Пепел',
    group: 'dark',
    description: 'Slate & Amber. Тёмный графит с янтарным акцентом.',
    accent: '#e0a030',
    bg: '#161617',
    surface: '#202022',
    text: '#e6e6e4',
  },
  {
    id: 'light-clay',
    label: 'Глина',
    group: 'light',
    description: 'Bone & Clay. Кремовая бумага и тёплый терракотовый акцент.',
    accent: '#b1502f',
    bg: '#f7f2ec',
    surface: '#fffbf5',
    text: '#211c18',
  },
  {
    id: 'dark-clay',
    label: 'Глина',
    group: 'dark',
    description: 'Bone & Clay. Тёмная глина с тёплым оранжево-терракотовым акцентом.',
    accent: '#e08050',
    bg: '#181310',
    surface: '#221b16',
    text: '#eae0d4',
  },
  {
    id: 'light-fog',
    label: 'Туман',
    group: 'light',
    description: 'Fog & Indigo. Прохладный серо-голубой фон и глубокий индиго-акцент.',
    accent: '#4145a8',
    bg: '#f4f5f8',
    surface: '#ffffff',
    text: '#191a1f',
  },
  {
    id: 'dark-fog',
    label: 'Туман',
    group: 'dark',
    description: 'Fog & Indigo. Тёмный туман с мягким сине-фиолетовым акцентом.',
    accent: '#8b8ef0',
    bg: '#12131a',
    surface: '#1b1c25',
    text: '#e3e4ea',
  },
  {
    id: 'light-sage',
    label: 'Полынь',
    group: 'light',
    description: 'Sage & Forest. Приглушённый зелёный фон и лесной акцент.',
    accent: '#3f7d54',
    bg: '#f2f4ef',
    surface: '#fbfcf9',
    text: '#1b1e19',
  },
  {
    id: 'dark-sage',
    label: 'Полынь',
    group: 'dark',
    description: 'Sage & Forest. Тёмная зелень с мягким травяным акцентом.',
    accent: '#68b47c',
    bg: '#101410',
    surface: '#181e18',
    text: '#e0e6de',
  },
  {
    id: 'light-midnight',
    label: 'Полночь',
    group: 'light',
    description: 'Midnight & Cyan. Светлый прохладный фон и бирюзово-циановый акцент.',
    accent: '#0d9488',
    bg: '#f3f6f7',
    surface: '#ffffff',
    text: '#141c22',
  },
  {
    id: 'dark-midnight',
    label: 'Полночь',
    group: 'dark',
    description: 'Midnight & Cyan. Глубокий тёмно-синий фон и яркий циановый акцент.',
    accent: '#4fd1c5',
    bg: '#10151b',
    surface: '#182129',
    text: '#e2e8ec',
  },
]

export const DEFAULT_THEME = 'light-parchment'
